taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:content
          - panel:nomenclature
          - panel:nomenclature-references
          - panel:etymology

        - - panel:map
          - panel:descendants
          - panel:stratigraphic-range
          - panel:gbif
          - panel:scrutiny
          - panel:statistics
  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  inaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - panel:inaturalist
