taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:content
          - panel:nomenclature
          - panel:nomenclature-references
          - panel:etymology

        - - panel:map
          - panel:descendants
          - panel:scrutiny
          - panel:statistics
  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  inaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - panel:inaturalist
  stratigraphic_range:
    label: 'Stratigraphic Range'
    rank_group: ['SpeciesGroup', 'GenusGroup', 'FamilyGroup']
    panels:
      - - - panel:stratigraphic-range
  gbif:
    label: 'GBIF'
    panels:
      - - - panel:gbif
  nhm:
    label: 'Natural History Museum'
    panels:
      - - - panel:nhm
